name: Fetch data from OpenStreetMap

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  fetch-osm-data:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch data from features, and save it to src/pages/features.json
        run: curl https://overpass-api.de/api/interpreter\?data\=%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3Barea%283600404159%29%2D%3E%2EsearchArea%3Bnwr%5B%22shop%22%3D%22second%5Fhand%22%5D%28area%2EsearchArea%29%3Bout%20geom%3B%0A > src/data/features.json

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update features.json"
          commit_options: "--no-verify"
  deploy:
    permissions:
      pages: write
      id-token: write
      contents: read
    uses: fivh-bergen/kart/.github/workflows/deploy.yml@main
