name: Fetch data from OpenStreetMap

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  fetch-osm-data:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v4
        name: Setup pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"

      - name: Fetch nodes from Overpass API
        run: pnpm fetch-nodes

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update features.json"
          commit_options: "--no-verify"
  deploy:
    permissions:
      pages: write
      id-token: write
      contents: read
    uses: fivh-bergen/kart/.github/workflows/deploy.yml@main
